project_id = "lyqcsclmauwmzipjiazs"

[functions.handle-stripe-webhook]
verify_jwt = false

[functions.suggest-categories]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.upload-to-google-drive]
verify_jwt = true

[functions.get-company-by-whatsapp]
verify_jwt = true
